### ISSUE TITLE
Issue date always 1 days before also cannot convert

### ISSUE THREAD

**Issue by hryer** [eFishery/json-reactform#14]
when choosing the date: 20-03-2020

the response will be :
"2020-03-19T17:00:00.000Z"

another example cases
 27-03-2020

the response will be :
"2020-03-26T17:00:00.000Z"

the time will be stuck at 17:00

**Comment by ans-4175** [comment]
This is not a bug, since you are provide date without time, it will accepted as 00:00 and I believe client is utc+7. Then it will subtract yours by -7 from 24, so it will be 17
